[package]
name = "moonshine-save"
version = "0.7.0"
edition = "2021"
license = "MIT"
description = "Save/Load framework for Bevy"
categories = ["game-development"]
keywords = ["bevy", "save", "load", "serde", "ron"]
readme = "README.md"
homepage = "https://github.com/Zeenobit/moonshine_save"
repository = "https://github.com/Zeenobit/moonshine_save"

[dependencies]
ron = "0.12"
serde = "1"
thiserror = "2"
bevy_app = "0.20.0-rc.2"
bevy_asset = "0.20.0-rc.2"
bevy_ecs = "0.20.0-rc.2"
bevy_log = "0.20.0-rc.2"
bevy_platform = "0.20.0-rc.2"
bevy_reflect = "0.20.0-rc.2"
bevy_world_serialization = "0.20.0-rc.2"
moonshine-util = "0.5"

[dev-dependencies]
bevy = "0.20.0-rc.2"
